Create draft page meetups
js-tasks-ru/vue-20201022_o-a-sushinskaya pull request #3
Opened 2020-11-15 23:27 UTC by sushka-oa

2020-11-15 23:33 UTC, jsru commented
Пожалуйста, не меняйте «системные» файлы.
          Задача не может считаться решенной, если были изменены файлы тестов или другие «системные» файлы.
          Следующие файлы были изменены:
```diff
- package.json — изменен
```

2020-11-16 09:12 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Meetup Page Draft
+ Задача добавлена, но требует ручной проверки
```

Добавляю преподавателя (@ShGKme) для код-ревью, посмотрим что он скажет :)

2020-11-16 13:18 UTC, ShGKme requested changes
Требуется избавиться от вызова методов в шаблоне

2020-11-16 13:18 UTC, ShGKme commented on 01-basics/02-MeetupPageDraft/index.html
> +                      class="meetup-agenda__dot"></span>
Лучше избегать вызова методов в шаблоне.
Здесь может быть простое выражение, либо свойство, либо вычисляемое свойство.

Метод - как обычная функция, будет вызываться каждый раз, когда будет происходить ререндеринг (когда vue встретит вызов метода в шаблоне). Вычисляемые свойства же будут перевычисляться  только тогда, когда изменяются свойства, от которых они зависят. Другими словами можно сказать, что computed - кэшируется.

Кроме того, это не декларативно. Нам требуется описать шаблон, который декларирует, описывает, какое отображение (HTML) мы хотим получить. А вызов метода - это императивный путь, мы говорим, что нужно сделать, чтобы получить данные, необходимые для формирования страницы.

2020-11-16 13:18 UTC, ShGKme commented on 01-basics/02-MeetupPageDraft/script.js
> +      meetupInfo: {}
Пустой объект - не частный случай объекта с описанием митапа. Хотя установка начального значения в {} избавляет от простых ошибок, она не избавляет от ошибок полностью, оставляя более трудно-находимые ошибки. Лучше начальным значением указать null и делать явные проверки

2020-11-16 13:18 UTC, ShGKme commented on 01-basics/02-MeetupPageDraft/script.js
> +const LOCALE = 'ru-RU';
Лучше использовать `navigator.language`, либо `undefined` и использовать локаль браузера, а не фиксированную.

2020-11-16 13:18 UTC, ShGKme commented on 01-basics/02-MeetupPageDraft/script.js
> +    },
Совсем простые выражения, которые нужны только в одном месте, можно писать прямо в шаблоне, чтобы не перегружать компонент вычисляемыми свойствами.

2020-11-16 17:57 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2020-11-16 18:15 UTC, sushka-oa commented on 01-basics/02-MeetupPageDraft/script.js
> +    },
Исправила

2020-11-16 18:15 UTC, sushka-oa commented on 01-basics/02-MeetupPageDraft/script.js
> +      meetupInfo: {}
Исправила

2020-11-16 18:16 UTC, sushka-oa commented on 01-basics/02-MeetupPageDraft/index.html
> +                      class="meetup-agenda__dot"></span>
Исправила

2020-11-16 18:56 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2020-11-16 21:26 UTC, ShGKme requested changes
Требуется ещё одно маленькое исправление.

Отсутствовать значения могут только в описании пунктов программы, а не самого митапа.
Из условия, наверное, не понятно... Полную схему можно посмотреть здесь: https://course-vue.javascript.ru/api/#/Meetups/MeetupsController_findById

Если в ответе выбрать Schema. Звёздочка означает, что значение обязательное.

Хотя хуже от лишних проверок, конечно, не будет.

2020-11-16 21:26 UTC, ShGKme commented on 01-basics/02-MeetupPageDraft/script.js
> +      return `--bg-url: url(${getMeetupCoverLink(this.meetupInfo?.imageId)})`;
В прошлый раз не заметил.
Если у митапа будет отсутствовать изображение, то это свойство с пустым некорректным url всё равно перебьёт значение `--bg-url` по умолчанию

2020-11-17 00:09 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
Компонент CounterButton
- CounterButton должен иметь числовой входной параметр count со значением 0 по умолчанию
- CounterButton должен рендерить кнопку с текстом count
- CounterButton должен иметь count 0 по умолчанию
- CounterButton должен порождать событие increment с увеличенным на 1 значением по клику
```
```diff
Meetup Page Draft
+ Задача добавлена, но требует ру��ной проверки
```

2020-11-17 06:30 UTC, ShGKme approved these changes
Принято 👍

2020-11-17 06:30 UTC, jsru commented
PR не может быть принят, обратитесь, пожалуйста, к преподавателю.

2020-11-17 21:11 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2020-11-17 23:01 UTC, ShGKme approved these changes
Принято 👍

2020-11-17 23:02 UTC, merged

2020-11-17 23:02 UTC, ShGKme commented
В этот раз полностью принято :)